dist: bionic

language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.13.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go get github.com/vektra/mockery/.../
  - mockery -dir domain/repository -name RecipeRepository
  - mockery -dir domain/repository -name RatingRepository
  - mockery -dir domain/interactor -name RecipeInteractor
  - mockery -dir domain/tool -name IdGenerator

script:
  - go test -v -race ./...
