dist: bionic

language: go

env:
  global:
    - GOX_FLAGS="-arch amd64"
    - TRAVIS_GO_VERSION=1.13.4

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go get github.com/vektra/mockery/.../
  - mockery -dir domain/repository -name RecipeRepository
  - mockery -dir domain/repository -name RatingRepository
  - mockery -dir domain/interactor -name RecipeInteractor
  - mockery -dir domain/tool -name IdGenerator

script:
  - go test -v -race ./...
